fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\UserBundle\Entity\User
  from_email:
    address: postmaster@webant.ru
    sender_name: WebAnt